### ISSUE TITLE
Laugh Score: 0.189660 - vol:0.0

### ISSUE THREAD

**Issue by Spandan-Madan** [ideo/LaughDetection#6]
No matter what I say into the mic, I get this as the output of live_inference.py

Am I doing something wrong?

**Comment by jelling** [comment]
How did you fix this? I have the same issue on Mac OS

**Comment by jelling** [comment]
I figured it out and I believe this is a MacOS issue, likely specific to Catalina and onward. 

The application needs access to the microphone but not all terminal environments yet request this access from MacOS.  I was using the terminal provided by VSCode and it did not. But I ran the same command using the OS provided Terminal application and microphone access was requested and then it ran as it should.
