### ISSUE TITLE
Questions about create subset of audioset

### ISSUE THREAD

**Issue by duyuanchao** [ideo/LaughDetection#9]
Hi, thanks for your excellent work.

I am very interested in creating a new subset of audioset. But it seems [AudiosetProcessing.ipynb](https://github.com/ideo/LaughDetection/blob/master/Notebooks/AudiosetProcessing.ipynb) is not finished yet?

**Comment by nsteins** [comment]
Sorry, something in one of the output cells was causing github's notebook renderer to quit half way through the notebook. I've cleared all the output cells and pushed it to the repo, so the full notebook should be visible now.

Thanks for catching that!
